2025-04-04 22:35:16,280 ERROR: Exception on /api/calculate [POST] [in C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\OneDrive\Рабочий стол\DPK_Sebestoimost Stable (2)\DPK_Sebestoimost Stable\DPK_Sebestoimost\app.py", line 339, in calculate
    result = calculate_metal(width, height, steps, material, has_platform, platform_depth, reinforcements_count, paint_consumption, frame_color)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\OneDrive\Рабочий стол\DPK_Sebestoimost Stable (2)\DPK_Sebestoimost Stable\DPK_Sebestoimost\app.py", line 113, in calculate_metal
    base_depth_profiles = 2 * step_depth * steps - 4 * profile_thickness
                                                       ^^^^^^^^^^^^^^^^^
NameError: name 'profile_thickness' is not defined
2025-04-04 22:36:10,874 ERROR: Exception on /api/calculate [POST] [in C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\OneDrive\Рабочий стол\DPK_Sebestoimost Stable (2)\DPK_Sebestoimost Stable\DPK_Sebestoimost\app.py", line 339, in calculate
    result = calculate_metal(width, height, steps, material, has_platform, platform_depth, reinforcements_count, paint_consumption, frame_color)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\OneDrive\Рабочий стол\DPK_Sebestoimost Stable (2)\DPK_Sebestoimost Stable\DPK_Sebestoimost\app.py", line 113, in calculate_metal
    base_depth_profiles = 2 * step_depth * steps - 4 * profile_thickness
                                                       ^^^^^^^^^^^^^^^^^
NameError: name 'profile_thickness' is not defined
2025-04-04 22:36:51,147 ERROR: Exception on /api/calculate [POST] [in C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\htcbu\OneDrive\Рабочий стол\DPK_Sebestoimost Stable (2)\DPK_Sebestoimost Stable\DPK_Sebestoimost\app.py", line 339, in calculate
  File "C:\Users\htcbu\OneDrive\Рабочий стол\DPK_Sebestoimost Stable (2)\DPK_Sebestoimost Stable\DPK_Sebestoimost\app.py", line 113, in calculate_metal
    base_width_profiles = 2 * width
                                    
NameError: name 'profile_thickness' is not defined
2025-04-04 22:37:06,117 ERROR: Ошибка обработки запроса: 'PROFILE_THICKNESS' [in C:\Users\htcbu\OneDrive\Рабочий стол\DPK_Sebestoimost Stable (2)\DPK_Sebestoimost Stable\DPK_Sebestoimost\app.py:346]
2025-04-04 22:38:28,601 ERROR: Ошибка обработки запроса: 'PROFILE_THICKNESS' [in C:\Users\htcbu\OneDrive\Рабочий стол\DPK_Sebestoimost Stable (2)\DPK_Sebestoimost Stable\DPK_Sebestoimost\app.py:346]
